steps:
  - id: build-images
    name: 'gcr.io/cloud-builders/docker'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    args: [ 'compose', 'build' ]

  - id: push-images
    name: 'gcr.io/cloud-builders/docker'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    args: [ 'compose', 'push' ]
