steps:

### Build Images
  - id: build-images
    name: 'gcr.io/cloud-builders/docker'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    args: [ 'compose', 'build' ]

### Push Images
  - id: push-images
    name: 'gcr.io/cloud-builders/docker'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    args: [ 'compose', 'push' ]

### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    substitutions:
    _GKE_CLUSTER: gke-cluster # default value
    _GKE_ZONE: us-central12 # default value
    script: |
      #!/bin/bash
      set -e
      gcloud container clusters get-credentials ${_GKE_CLUSTER} \
        --project $PROJECT_ID \
        --zone ${_GKE_ZONE} 
      cd k8s
      kubectl apply -f . -n default
