version: '3.8'
services:
  redis_server:
    container_name: redis_server
    image: 'redislabs/redismod'
    volumes:
      - redis_data:/data
    ports: # enable to visualize data in redis insight
      - '${REDIS_INSIGHT_PORT}:6379'

  mongodb_server:
    container_name: mongodb_server
    image: 'mongo'
    volumes:
      - mongodb_data:/data/db
    ports: # enable to visualize data in mongodb compass
      - '${MONGODB_COMPASS_PORT}:27017'

  mongodb_seed:
    container_name: mongodb_seed
    build:
      context: ./
      dockerfile: dockerfile-mongodb-seed
      args:
        BUILD_BASE_PATH: database
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-mongodb_seed
    env_file:
      - ./.env
    depends_on:
      - mongodb_server

  cdn:
    container_name: cdn
    build:
      context: ./
      dockerfile: dockerfile-cdn
      args:
        BUILD_BASE_PATH: cdn
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-cdn
    ports:
      - '${CDN_PORT}:80'

  orders_service:
    container_name: orders_service
    build:
      context: ./
      dockerfile: dockerfile-server
      args:
        BUILD_BASE_PATH: server/src/services/orders
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-orders_service
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server

  order_history_service:
    container_name: order_history_service
    build:
      context: ./
      dockerfile: dockerfile-server
      args:
        BUILD_BASE_PATH: server/src/services/order-history
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-order_history_service
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server

  products_service:
    container_name: products_service
    build:
      context: ./
      dockerfile: dockerfile-server
      args:
        BUILD_BASE_PATH: server/src/services/products
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-products_service
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server

  payments_service:
    container_name: payments_service
    build:
      context: ./
      dockerfile: dockerfile-server
      args:
        BUILD_BASE_PATH: server/src/services/payments
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-payments_service
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server
      - orders_service

  api_gateway:
    container_name: api_gateway
    build:
      context: ./
      dockerfile: dockerfile-server
      args:
        BUILD_BASE_PATH: server/src/api-gateway
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-api_gateway
    ports:
      - '${API_GATEWAY_PORT}:3000'
    env_file:
      - ./.env
    depends_on:
      - orders_service
      - order_history_service
      - products_service

  client:
    container_name: client
    build:
      context: ./
      dockerfile: dockerfile-client
      args:
        BUILD_BASE_PATH: client/nextjs
        API_GATEWAY_URI: ${API_GATEWAY_URI}
        NEXT_PUBLIC_API_GATEWAY_URI: ${NEXT_PUBLIC_API_GATEWAY_URI}
    image: gcr.io/${PROJECT_ID}/redis-ms-cqrs-client
    ports:
      - '${FRONTEND_CLIENT_PORT}:4200'
    env_file:
      - ./.env
    stdin_open: true # -i input flag
    tty: true # -t terminal flag
    depends_on:
      - api_gateway
      - cdn

volumes:
  redis_data:
  mongodb_data:
